apiVersion: v1
kind: pod
metadata:
  name: pod-pv-1
spec:
  containers:
    - name: nginx-container
      image: nginx:lastest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /volume-container
          name: pv-1-container
    
  volumes:
  - name: pv-1-container
    persistentVolumeClaim:
      claimName: pvc-1
        
